const CHANGE_FORMULA_EDITOR_FOCUS = 'CHANGE_FORMULA_EDITOR_FOCUS';
const GET_FORMULA_EDITOR_STYLE = 'GET_FORMULA_EDITOR_STYLE';
const CHANGE_FORMULA_EDITOR_BUTTON_STATE = 'CHANGE_FORMULA_EDITOR_BUTTON_STATE';

export {CHANGE_FORMULA_EDITOR_FOCUS, GET_FORMULA_EDITOR_STYLE, CHANGE_FORMULA_EDITOR_BUTTON_STATE};